# Generated by Django 2.2.6 on 2019-10-29 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_admin_admin_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('Remove Member', 'Remove a member'), ('Verify Event', 'Verify an event'), ('Approve Member', 'Approve a member'), ('Restrict Member', 'Restrict a member'), ('Update Member', 'Update a member')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=40)),
                ('user_type', models.CharField(choices=[('Faculty', 'Faculty'), ('Staff', 'Staff'), ('Student', 'Student')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User_logins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hashes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('hashval', models.CharField(max_length=128)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='AdminActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now=True)),
                ('action_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Actions')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Admin')),
            ],
        ),
    ]
