# Generated by Django 2.2.6 on 2019-11-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191113_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_logins',
            options={'managed': False},
        ),
    ]
