# Generated by Django 2.2.6 on 2019-11-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191113_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='adminactions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='hashes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'managed': False},
        ),
    ]
